---
# Defaults for the picoCTF-web role. These are the lowest priority variables
# and can easily be overridden in group_vars, host_vars, or the command line.

# pico_base_dir set in common.yml
shell_manager_dir:  "{{pico_base_dir}}/picoCTF-shell"

###
# wetty configuration
###
wetty_js_path: "/opt/wetty/node_modules/wetty.js"

# configure nginx
shell_site_config_name: "shell"
wetty_port: "4242"
wetty_server_path: "http://127.0.0.1:{{ wetty_port }}/"

# problem settings
deb_dir:    "/picoCTF-debs"
bundle_dir: "/picoCTF-bundles"

##
# Problem Settings
# These will only be used if `problem_source_dirs` and `bundles` are not
# specified in an environmental configuration AND `auto_load_problems` is True
##
problem_source_dirs:
  - "{{ pico_base_dir }}/problems/examples/binary-exploitation/buffer-overflow-1"
  - "{{ pico_base_dir }}/problems/examples/cryptography/ecb-1"
  - "{{ pico_base_dir }}/problems/examples/web-exploitation/sql-injection-1"
  - "{{ pico_base_dir }}/problems/examples/on-demand"

bundles:
  - "{{ pico_base_dir }}/problems/bundles/challenge-sampler.json"
  - "{{ pico_base_dir }}/problems/bundles/on-demand.json"

# SSL requires cert and vault-encrypted key
enable_shell_ssl: False
enable_certbot  : False

enable_shell_proxy: True
