---
# Playbook that configures nginx for picoCTF-web
# This is the base picoCTF web nginx configuration

- name: Configure nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify :
    - nginx restart

- name: Add nginx.service override directory
  file:
    path: /etc/systemd/system/nginx.service.d/
    state: directory
    mode: 0755

- name: Copy NOLIMIT override file
  copy:
    src: override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify :
    - nginx restart

# Must occur before picoCTF configuration is added to ensure the
# referenced keys exist.
- name: Request certificate (certbot)
  vars:
    certbot_domain: "{{nginx_server_name}}"
  include_role:
    name: certbot
    tasks_from: request_certificates
  when: enable_certbot | bool

- name: Add picoCTF site configuration to nginx
  template: 
    src: ctf.nginx.j2
    dest: "/etc/nginx/sites-available/{{ pico_site_config_name }}"
    backup: yes
    owner: root
    group: root
    mode: 0644
  no_log: True
  notify :
    - nginx reload

# HTTP Basic Auth used to secure remote testing competition sites
- name: Setup HTTP basic auth
  htpasswd:
    path: "/etc/nginx/.htpasswd"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    owner: www-data
    group: www-data
    mode: 0640
  no_log: True
  with_items: "{{ htpasswd_accounts }}"
  when: enable_basic_auth

# Install SSL cert and key for nginx
- name: Copy SSL cert
  copy:
    src: ssl-pico.chained.crt
    dest: /etc/ssl/certs/ssl-pico.chained.crt
    owner: root
    group: root
    mode: 0644
  when: enable_web_ssl | bool

- name: Copy SSL key
  copy:
    src: ssl-pico.key.vault_encrypted
    dest: /etc/ssl/private/ssl-pico.key
    owner: root
    group: root
    mode: 0644
  when: enable_web_ssl | bool

- name: Enable picoCTF site configuration
  file:
    src: "/etc/nginx/sites-available/{{ pico_site_config_name }}"
    dest: "/etc/nginx/sites-enabled/{{ pico_site_config_name }}"
    owner: root
    group: root
    state: link
  notify :
    - nginx restart

- name: Disable default nginx site configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
